# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V56wzRtK7GvexMlRF1IVHZ_yfLgBimEC
"""

"""
=============================================================
  SIM Lab01 — Millora A + B
  Demanda variable + Capacitat finita i passatgers rebutjats
  3 busos, 5 parades, 24h (24000s, on 1000s = 1h)
  Capacitat màxima: 100 passatgers per bus
  Passatgers baixen amb destinació aleatòria
=============================================================
  ✅ Llest per executar a Google Colab sense cap modificació
=============================================================
"""

import random, heapq, statistics
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

# ── Franges horàries ─────────────────────────────────────────────────────────
def demand_multiplier(time):
    h = time / 1000
    if h < 6:    return 0.15   # Nit
    elif h < 9:  return 1.5    # Matí punta
    elif h < 15: return 1.0    # Dia normal
    elif h < 18: return 2.5    # Tarda punta
    elif h < 22: return 1.0    # Vespre
    else:        return 0.15   # Nit

# ── Simulació ─────────────────────────────────────────────────────────────────
def simulate(seed=42, n_buses=3, n_stops=5, sim_time=24000, bus_capacity=100):
    random.seed(seed)
    np.random.seed(seed)

    base_rates   = [1/60, 1/30, 1/30, 1/30, 1/60]
    travel_times = [(120,10),(150,12),(150,12),(120,10),(180,15)]

    # Cua de passatgers: llista d'arrival_times per parada
    waiting          = [[] for _ in range(n_stops)]
    last_pax_update  = [0.0] * n_stops
    last_bus_at_stop = [None] * n_stops
    bus_load         = [0] * n_buses   # passatgers actuals a cada bus

    # Recollida de dades
    headway_data   = {s: {'times': [], 'headways': []}  for s in range(n_stops)}
    rejected_data  = {s: {'times': [], 'rejected': []}  for s in range(n_stops)}
    occupancy_data = {b: {'times': [], 'occupancy': []} for b in range(n_buses)}
    waiting_times  = []   # temps d'espera de cada passatger que puja

    # Inicialització: busos espaiats 200s
    events = []
    for b in range(n_buses):
        heapq.heappush(events, (b * 200, b, 'arrive', 0))

    # ── Bucle principal ───────────────────────────────────────────────────────
    while events:
        time, bus, action, stop = heapq.heappop(events)
        if time > sim_time:
            break

        # 1) Acumular passatgers nous (integració per trossos de 50s)
        dt = time - last_pax_update[stop]
        if dt > 0:
            t = last_pax_update[stop]
            accumulated = 0.0
            step = 50
            while t < time:
                t_end = min(t + step, time)
                rate = base_rates[stop] * demand_multiplier(t)
                accumulated += rate * (t_end - t)
                t = t_end
            n_new = np.random.poisson(max(0, accumulated))
            for _ in range(n_new):
                waiting[stop].append(time - random.uniform(0, dt))
            last_pax_update[stop] = time

        # 2) Headway
        if last_bus_at_stop[stop] is not None:
            hw = time - last_bus_at_stop[stop]
            headway_data[stop]['times'].append(time)
            headway_data[stop]['headways'].append(hw)
        last_bus_at_stop[stop] = time

        # 3) Baixada: cada passatger té prob 1/(n_stops-1) de baixar
        if bus_load[bus] > 0:
            p_alight = 1.0 / (n_stops - 1)
            alighting = np.random.binomial(bus_load[bus], p_alight)
            bus_load[bus] -= min(alighting, bus_load[bus])

        # 4) Pujada amb capacitat finita
        free_seats  = bus_capacity - bus_load[bus]
        n_waiting   = len(waiting[stop])
        n_boarding  = min(free_seats, n_waiting)
        n_rejected  = n_waiting - n_boarding

        # Temps d'espera (pugen els que porten més estona)
        boarders = sorted(waiting[stop])[:n_boarding]
        for arr_t in boarders:
            wt = time - arr_t
            if wt >= 0:
                waiting_times.append(wt)

        # Rebutjats queden a la cua amb el seu arrival_time original
        waiting[stop] = sorted(waiting[stop])[n_boarding:]
        bus_load[bus] += n_boarding

        rejected_data[stop]['times'].append(time)
        rejected_data[stop]['rejected'].append(n_rejected)
        occupancy_data[bus]['times'].append(time)
        occupancy_data[bus]['occupancy'].append(bus_load[bus])

        # 5) Temps d'aturada (PMR: 5% dels passatgers)
        dwell = 0
        for _ in range(n_boarding):
            if random.random() < 0.05:
                dwell += random.uniform(8, 15)
            else:
                dwell += random.uniform(2, 4)

        # 6) Viatge a la següent parada
        next_stop = (stop + 1) % n_stops
        mean_t, std_t = travel_times[stop]
        travel = max(60, random.gauss(mean_t, std_t))
        heapq.heappush(events, (time + dwell + travel, bus, 'arrive', next_stop))

    return headway_data, rejected_data, occupancy_data, waiting_times

# ── Execució ──────────────────────────────────────────────────────────────────
print("Executant simulació...")
hd, rd, od, wt = simulate(seed=42)

print("\n=== RESULTATS ===")
print(f"  Passatgers servits:           {len(wt)}")
if wt:
    print(f"  Temps d'espera mitjà:         {statistics.mean(wt):.1f}s")
    print(f"  Temps d'espera mediana:       {statistics.median(wt):.1f}s")
    print(f"  Temps d'espera màxim:         {max(wt):.1f}s")
total_rejected = sum(sum(rd[s]['rejected']) for s in rd)
print(f"  Total passatgers rebutjats:   {total_rejected}")

# ── Configuració dels gràfics ─────────────────────────────────────────────────
shade_franges = [
    (0,     6000,  '#2c3e50', 0.12),
    (6000,  9000,  '#e67e22', 0.15),
    (9000,  15000, '#f1c40f', 0.10),
    (15000, 18000, '#e74c3c', 0.15),
    (18000, 22000, '#f1c40f', 0.10),
    (22000, 24000, '#2c3e50', 0.12),
]
hours   = list(range(0, 25, 2))
xticks  = [h * 1000 for h in hours]
xlabels = [f'{h}h' for h in hours]

def shade_axes(axes_list):
    for ax in axes_list:
        for t0, t1, col, a in shade_franges:
            ax.axvspan(t0, t1, alpha=a, color=col)
        ax.set_xticks(xticks)
        ax.set_xticklabels(xlabels)
        ax.set_xlim(0, 24000)
        ax.grid(True, alpha=0.2)

legend_patches = [
    mpatches.Patch(color='#2c3e50', alpha=0.5, label='Nit ×0.15'),
    mpatches.Patch(color='#e67e22', alpha=0.5, label='Matí punta ×1.5'),
    mpatches.Patch(color='#f1c40f', alpha=0.5, label='Dia ×1.0'),
    mpatches.Patch(color='#e74c3c', alpha=0.5, label='Tarda punta ×2.5'),
]

# ══════════════════════════════════════════════════════════════════════════════
# FIGURA 1 — Headway + Rebutjats + Ocupació
# ══════════════════════════════════════════════════════════════════════════════
fig1, axes1 = plt.subplots(4, 1, figsize=(15, 14), sharex=True)
shade_axes(axes1)

# (a) Headway parada 2 (cèntrica)
ax = axes1[0]
ax.plot(hd[2]['times'], hd[2]['headways'], 'b-', lw=0.8, marker='.', ms=2)
ax.set_ylabel('Headway (s)')
ax.set_title('Headway — Parada 2 (cèntrica, λ=1/30)', fontsize=11)

# (b) Headway parada 0 (perifèrica)
ax = axes1[1]
ax.plot(hd[0]['times'], hd[0]['headways'], 'r-', lw=0.8, marker='.', ms=2)
ax.set_ylabel('Headway (s)')
ax.set_title('Headway — Parada 0 (perifèrica, λ=1/60)', fontsize=11)

# (c) Passatgers rebutjats per parada
ax = axes1[2]
colors_stops = ['#e74c3c','#e67e22','#3498db','#2ecc71','#9b59b6']
for s in range(5):
    if rd[s]['times']:
        ax.bar(rd[s]['times'], rd[s]['rejected'],
               width=80, alpha=0.7, color=colors_stops[s], label=f'Parada {s}')
ax.set_ylabel('Passatgers rebutjats')
ax.set_title('Passatgers rebutjats per bus per parada (capacitat 100 pax)', fontsize=11)
ax.legend(loc='upper left', fontsize=8, ncol=5)

# (d) Ocupació dels 3 busos
ax = axes1[3]
bus_colors = ['#1abc9c','#e74c3c','#3498db']
for b in range(3):
    if od[b]['times']:
        ax.plot(od[b]['times'], od[b]['occupancy'],
                color=bus_colors[b], lw=0.8, alpha=0.85, label=f'Bus {b}')
ax.axhline(100, color='black', lw=1, linestyle='--', label='Capacitat màx. (100)')
ax.set_ylabel('Passatgers a bord')
ax.set_title('Ocupació dels busos al llarg del dia', fontsize=11)
ax.legend(loc='upper left', fontsize=8, ncol=4)
ax.set_xlabel('Hora del dia')
ax.set_ylim(0, 115)

fig1.legend(handles=legend_patches, loc='lower center', ncol=4,
            fontsize=9, bbox_to_anchor=(0.5, -0.01))
plt.suptitle('Millora A + B: Demanda variable + Capacitat finita (100 pax)\n3 busos, 5 parades, 24h',
             fontsize=13, fontweight='bold')
plt.tight_layout(rect=[0, 0.03, 1, 1])
plt.show()

# ══════════════════════════════════════════════════════════════════════════════
# FIGURA 2 — Temps d'espera + Headway per franja
# ══════════════════════════════════════════════════════════════════════════════
fig2, axes2 = plt.subplots(1, 2, figsize=(14, 5))

# (a) Histograma temps d'espera global
ax = axes2[0]
ax.hist(wt, bins=60, color='steelblue', edgecolor='white', linewidth=0.3)
ax.axvline(statistics.mean(wt), color='red', lw=1.5, linestyle='--',
           label=f'Mitjana: {statistics.mean(wt):.0f}s')
ax.axvline(statistics.median(wt), color='orange', lw=1.5, linestyle='-.',
           label=f'Mediana: {statistics.median(wt):.0f}s')
ax.set_xlabel("Temps d'espera (s)")
ax.set_ylabel('Nombre de passatgers')
ax.set_title("Distribució del temps d'espera dels passatgers", fontsize=11)
ax.legend()
ax.grid(True, alpha=0.2)

# (b) Boxplot headway per franja (proxy temps d'espera)
franges_labels = ['Nit\n(0-6h)', 'Matí\npunta\n(6-9h)', 'Dia\n(9-15h)',
                  'Tarda\npunta\n(15-18h)', 'Vespre\n(18-22h)', 'Nit\n(22-24h)']
franges_ranges = [(0,6000),(6000,9000),(9000,15000),(15000,18000),(18000,22000),(22000,24000)]
franja_colors  = ['#3498db','#e67e22','#f1c40f','#e74c3c','#f1c40f','#3498db']

hw_per_franja = []
for t0, t1 in franges_ranges:
    hws = [h for t, h in zip(hd[2]['times'], hd[2]['headways']) if t0 <= t < t1]
    hw_per_franja.append(hws if hws else [0])

bp = axes2[1].boxplot(hw_per_franja, patch_artist=True, tick_labels=franges_labels)
for patch, color in zip(bp['boxes'], franja_colors):
    patch.set_facecolor(color)
    patch.set_alpha(0.7)
axes2[1].set_ylabel('Headway (s) — Parada 2')
axes2[1].set_title("Distribució del headway per franja horària\n(proxy del temps d'espera)", fontsize=11)
axes2[1].grid(True, alpha=0.2)

plt.suptitle("Millora B: Anàlisi de temps d'espera i regularitat", fontsize=12, fontweight='bold')
plt.tight_layout()
plt.show()

# ── Estadístiques per franja ──────────────────────────────────────────────────
print(f"\n{'Franja':<25} {'Headway P2':>12} {'Std':>8} {'Rebutjats P2':>14} {'N':>5}")
print("-" * 65)
for label, (t0, t1) in zip(franges_labels, franges_ranges):
    label_clean = label.replace('\n', ' ')
    hws = [h for t, h in zip(hd[2]['times'], hd[2]['headways']) if t0 <= t < t1]
    rej = [r for t, r in zip(rd[2]['times'], rd[2]['rejected']) if t0 <= t < t1]
    hw_m  = f"{statistics.mean(hws):.0f}s"  if len(hws) > 1 else "—"
    hw_s  = f"{statistics.stdev(hws):.0f}s" if len(hws) > 1 else "—"
    rej_s = f"{sum(rej)}"                    if rej          else "0"
    print(f"{label_clean:<25} {hw_m:>12} {hw_s:>8} {rej_s:>14} {len(hws):>5}")

